# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20160315_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='comment',
            new_name='song',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='author',
            field=models.CharField(default='', max_length=250),
        ),
    ]
