# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20160317_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='is_piano',
            field=models.BooleanField(default=False),
        ),
    ]
